version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dh_supplier_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: supplier_user
      POSTGRES_PASSWORD: supplier_pass
      POSTGRES_DB: supplier_portal
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
